Repository imdangg/imdang-iOS, pull requests merged in 2024-12, with the labels that each got.

#28 Feat: 탐색뷰 인사이트 섹션 추가, 배너 추가, 검색창, 지도 버튼, 패스권 모달 추가
  Projects/imdang/Resources/Assets.xcassets/Banner.imageset/Banner.svg
  Projects/imdang/Resources/Assets.xcassets/Banner.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/Blob.imageset/Blob.svg
  Projects/imdang/Resources/Assets.xcassets/Blob.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/Cancle.imageset/Cancle.svg
  Projects/imdang/Resources/Assets.xcassets/Cancle.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/magnifier.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/magnifier.imageset/magnifier.svg
  Projects/imdang/Resources/Assets.xcassets/mapButton.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/mapButton.imageset/mapButton.svg
  Projects/imdang/Resources/Assets.xcassets/passTicket.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/passTicket.imageset/passTicket.svg
  Projects/imdang/Sources/Common/Cell/InsightCollectionCell.swift
  Projects/imdang/Sources/Presentation/Home/View/HomeContainerViewController.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/BannerView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/Cell/PagingFooterView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/Cell/SearchingSectionHeaderView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/Cell/SectionSeparatorView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchBoxView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchingViewController.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/TicketModalViewController.swift
  Projects/imdang/Sources/Utils/Extensions/UILabel +.swift
  Projects/imdang/Sources/Utils/Extensions/UIViewController +.swift
Labels: ✨Feature, 🫧 daejin

#30 Fix: 레이아웃 수정 및 페이지 인디케이터 추가
  Projects/imdang/Sources/Presentation/Home/View/HomeContainerViewController.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/Cell/PagingFooterView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/Cell/SearchingSectionHeaderView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchBoxView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchingViewController.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/TicketModalViewController.swift
Labels: 🔨 Refactor, 🫧 daejin

#37 Feat: 보관함 UI 구현
  Projects/imdang/Resources/Assets.xcassets/backButton.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/backButton.imageset/backButton.svg
  Projects/imdang/Resources/Assets.xcassets/chevronDown.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/chevronDown.imageset/chevronDown.svg
  Projects/imdang/Resources/Assets.xcassets/mapButtonGray.imageset/Contents.json
  Projects/imdang/Resources/Assets.xcassets/mapButtonGray.imageset/mapButtonGray.svg
  Projects/imdang/Sources/Common/ImageTextButton.swift
  Projects/imdang/Sources/Common/RadioButton.swift
  Projects/imdang/Sources/Presentation/Home/View/HomeContainerViewController.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchBoxView.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchingViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/AreaListViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/AreaModalViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/Cell/AreaListTableCell.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/Cell/AreaModalTableCell.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/Cell/InsightHeaderView.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/Cell/LocationBoxCollectionCell.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/Cell/LocationBoxHeaderView.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/InsightTableViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/StorageBoxViewController.swift
  Projects/imdang/Sources/Presentation/TabBar/TabBarController.swift
  Projects/imdang/Sources/Utils/Extensions/UIViewController +.swift
Labels: ✨Feature, 🫧 daejin

#38 Add InsightView Base
  Projects/imdang/Sources/App/SceneDelegate.swift
  Projects/imdang/Sources/Presentation/Insight/InsightViewController.swift
  Projects/imdang/Sources/Presentation/Insight/subView/WebViewController.swift
  Projects/imdang/Sources/Presentation/TabBar/TabBarController.swift
  Projects/imdang/Sources/Presentation/UserInfoEntry/View/UserInfoEntryViewController.swift
Labels: ✨Feature, 🌈 daye

#40 BugFix: 탭바 레이아웃 수정
  Projects/imdang/Project.swift
  Projects/imdang/Sources/Presentation/Home/View/Searching/SearchingViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/AreaListViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/InsightTableViewController.swift
  Projects/imdang/Sources/Presentation/StorageBox/View/StorageBoxViewController.swift
  Projects/imdang/Sources/Presentation/TabBar/TabBarController.swift
  Projects/imdang/Sources/Utils/Extensions/UIDevice.swift
  imdangg/Sources/Presentation/Common/View/WideButtonView.swift
  imdangg/Sources/Presentation/UserInfoEntry/UserInfoEntryViewController.swift
  imdangg/Sources/Presentation/UserInfoEntry/UserInfoEntryViewReactor.swift
  imdangg/Sources/Presentation/UserInfoEntry/View/SubView/GenderButtonView.swift
  imdangg/Sources/Presentation/UserInfoEntry/View/SubView/UserInfoEntryHeaderView.swift
  imdangg/Sources/Presentation/UserInfoEntry/View/UserInfoEntryView.swift
  imdangg/Sources/Utils/Extensions/Color +.swift
  imdangg/Sources/Utils/Extensions/UIViewController + .swift
Labels: 🐞 BugFix, 🫧 daejin
