Repository imdangg/imdang-iOS, pull requests merged in 2024-11, with the labels that each got.

#3 Fix: 프로젝트 파일 삭제
  Imdangg.xcodeproj/project.pbxproj
  Imdangg.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Imdangg.xcodeproj/xcshareddata/xcschemes/imdangg.xcscheme
  imdangg.xcworkspace/.tuist-generated
  imdangg.xcworkspace/contents.xcworkspacedata
  imdangg.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  imdangg.xcworkspace/xcshareddata/xcschemes/imdangg-Workspace.xcscheme
Labels: 🐞 BugFix, 대즨님

#17 Feat: 홈탭 뷰 기본 구조 생성
  Derived/Sources/TuistAssets+Imdang.swift
  imdang/Resources/Assets.xcassets/ToolBar/Alarm.imageset/Alarm.svg
  imdang/Resources/Assets.xcassets/ToolBar/Alarm.imageset/Contents.json
  imdang/Resources/Assets.xcassets/ToolBar/Contents.json
  imdang/Resources/Assets.xcassets/ToolBar/Person.imageset/Contents.json
  imdang/Resources/Assets.xcassets/ToolBar/Person.imageset/Person.svg
  imdang/Sources/App/SceneDelegate.swift
  imdang/Sources/Presentation/Home/View/EmptyView.swift
  imdang/Sources/Presentation/Home/View/HomeContainerViewController.swift
  imdang/Sources/Presentation/Home/View/ViewController.swift
  imdang/Sources/Presentation/Signin/View/OnboardingPageViewController.swift
  imdang/Sources/Presentation/TabBar/TabBarController.swift
Labels: ✨Feature, 🫧 daejin

#15 Feat: 카카오 로그인 로직 추가
  Project.swift
  Tuist/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  Tuist/Package.resolved
  Tuist/Package.swift
  imdang/Sources/App/AppDelegate.swift
  imdang/Sources/App/SceneDelegate.swift
  imdang/Sources/Presentation/Signin/View/SigninViewController.swift
  imdang/Sources/Presentation/Signin/ViewModel/SigninReactor.swift
Labels: ✨Feature, 🫧 daejin

#19 Feat: Apple login
  imdang/Sources/App/SceneDelegate.swift
  imdang/Sources/Presentation/Signin/View/SigninViewController.swift
  imdang/Sources/Presentation/Signin/ViewModel/SigninReactor.swift
  imdang/Sources/Services/AppleLoginService.swift
  imdang/imdang.entitlements
Labels: ✨Feature, 🌈 daye

#20 Feat: UserInfoEntryView
  imdang/Sources/App/SceneDelegate.swift
  imdang/Sources/Common/CommonButton.swift
  imdang/Sources/Common/CommonTextField.swift
  imdang/Sources/Presentation/Signin/View/OnboardingPageViewController.swift
  imdang/Sources/Presentation/UserInfoEntry/SubView/UserInfoEntryHeaderView.swift
  imdang/Sources/Presentation/UserInfoEntry/View/UserInfoEntryViewController.swift
  imdang/Sources/Presentation/UserInfoEntry/ViewModel/UserInfoEntryReactor.swift
  imdang/Sources/Utils/Extensions/Color +.swift
  imdang/Sources/Utils/Extensions/UIViewController +.swift
  imdangg/Sources/Presentation/Common/View/WideButtonView.swift
  imdangg/Sources/Presentation/UserInfoEntry/UserInfoEntryViewController.swift
  imdangg/Sources/Presentation/UserInfoEntry/UserInfoEntryViewReactor.swift
  imdangg/Sources/Presentation/UserInfoEntry/View/SubView/GenderButtonView.swift
  imdangg/Sources/Presentation/UserInfoEntry/View/SubView/UserInfoEntryHeaderView.swift
  imdangg/Sources/Presentation/UserInfoEntry/View/UserInfoEntryView.swift
  imdangg/Sources/Utils/Extensions/Color +.swift
  imdangg/Sources/Utils/Extensions/UIViewController + .swift
Labels: ✨Feature, 🌈 daye

#25 Feat: 구글 로그인 추가, 로그인 서비스 분리
  Projects/imdang/Project.swift
  Projects/imdang/Sources/App/AppDelegate.swift
  Projects/imdang/Sources/App/SceneDelegate.swift
  Projects/imdang/Sources/Presentation/Signin/View/SigninViewController.swift
  Projects/imdang/Sources/Presentation/Signin/ViewModel/SigninReactor.swift
  Projects/imdang/Sources/Services/GoogleLoginService.swift
  Projects/imdang/Sources/Services/KakaoLoginService.swift
  Projects/imdang/Sources/Utils/Extensions/UIApplication +.swift
  Projects/imdang/Sources/Utils/Extensions/Url +.swift
Labels: ✨Feature, 🫧 daejin

#26 Feat: 폰트 documentation comment 추가
  Projects/imdang/Sources/Utils/Extensions/Fonts +.swift
Labels: ✨Feature, 🫧 daejin
